### ISSUE TITLE
API for adding components

### ISSUE THREAD

**Issue by iamwillbar** [amzn/oss-attribution-builder#14] opened 2017-08-08 20:37 UTC
We've collected information about many components from other sources and would like to be able to add them programmatically. We'd need an API for getting, adding, and updating components.

**Comment by jpeddicord** [comment] 2017-08-09 19:39
Agreed. Pre-filling data would be useful, and the only way to do that at the moment is to make a dummy project and attach packages to it.

**Comment by sschuberth** [comment] 2019-05-02 07:32
To chime it, having an API would be awesome so we could add the oss-attribution-builder as a reporter to the [OSS Review Toolkit](https://github.com/heremaps/oss-review-toolkit).

**Comment by jpeddicord** [comment] 2019-09-25 21:24
Missed closing this out -- this is included in the attribution builder now :)

You can see API documentation while the service is running at `/api/docs`; it's a Swagger model. Also available here: https://github.com/amzn/oss-attribution-builder/blob/master/docs/openapi.yaml

**Closed by jpeddicord** 2019-09-25 21:24 UTC
Labels: enhancement

**Comment by julscha** [comment] 2019-10-23 14:53
Thanks for adding this! :) Going through the API I noticed that "attach a package to the project" requires a "packageId" (which apparently can be any number<=total amount of packages in database)
Attaching this new package then returns the actual "packageId" of the new package created in the attribution-builder database.
I don't understand yet, why "packageId" is required at all, and new packages are never checked for duplicates.
Let's say my project already has: 
_"packageId": "1"
"name": "Pkg1"
"version": "1.0.0"_
and
_"packageId":"2"
"name":"Pkg2"
"version":"1.0.0"_

Attaching
_"packageId":"1"
"name":"Pkg2"
"version":"1.0.0"_
simply attaches a duplicate of "Pgk2" to my project (which I can't delete via the API) and returns _"packageId":"3"_

This might be obvious for someone else, but I don't see the reason for this yet.
